---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 10.10.10.1
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.12
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.13
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.14
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.15
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.10.10.1
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.12
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.13
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.14
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 10.10.10.15
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - port: 1
